import type { ImageConfig, PosterConfig } from "@/types/poster";

const image = (src: string, x: number, y: number, width: number, scale = 1): ImageConfig => ({
  src,
  x,
  y,
  width,
  scale,
  opacity: 1,
  borderRadius: 22,
  borderWidth: 0,
  borderColor: "#f4c96b",
  shadowBlur: 18,
  shadowColor: "#071634",
});

export const DEFAULT_POSTER_CONFIG: PosterConfig = {
  template: "template-1",
  companyName: "SYABAS99",
  companyLogo: image("/assets/company-logo.png", 627, 58, 290),
  gameLogoLeft: { ...image("/assets/game-left.png", 185, 190, 215), borderWidth: 2 },
  gameLogoRight: { ...image("/assets/game-right.png", 1069, 190, 215), borderWidth: 2 },
  person: { ...image("/assets/person.png", 627, 238, 590), shadowBlur: 35, shadowColor: "#d99a24" },
  background: {
    src: "/assets/background.jpg",
    x: 0,
    y: 0,
    scale: 1,
    brightness: 0,
    contrast: 10,
    blur: 0,
    overlay: 0.14,
  },
  masterAmount: "1096.80",
  syncAmounts: true,
  withdraw: {
    title: "WITHDRAW",
    orderId: "#17056784543",
    amount: "1096.80",
    amountColor: "#087f6c",
    amountFontSize: 36,
    amountFontWeight: 900,
    date: "2026-08-14",
    time: "18:46",
    x: 55,
    y: 345,
    scale: 1,
  },
  success: {
    title: "Withdraw Successful",
    amount: "1096.8",
    amountColor: "#187f6a",
    description1: "Point cuci berjaya. Baki sudah transfer masuk bank anda.",
    description2: "ONG ONG bossku 🔥💪",
    x: 790,
    y: 338,
    scale: 1,
  },
  headline: {
    line1: {
      text: "TANIAH BOSS",
      x: 627,
      y: 910,
      scale: 1,
      fontSize: 108,
      fontWeight: 900,
      fontFamily: "Impact, Arial Black, sans-serif",
      fill: "#ffffff",
      stroke: "#164a9a",
      strokeWidth: 8,
      shadowColor: "#071a40",
      shadowBlur: 14,
    },
    cuci: {
      text: "CUCI",
      x: 238,
      y: 1025,
      scale: 1,
      fontSize: 92,
      fontWeight: 900,
      fontFamily: "Impact, Arial Black, sans-serif",
      fill: "#ffffff",
      stroke: "#164a9a",
      strokeWidth: 7,
      shadowColor: "#061a3e",
      shadowBlur: 12,
    },
    amount: {
      text: "",
      value: "1096",
      x: 520,
      y: 1025,
      scale: 1,
      fontSize: 92,
      fontWeight: 900,
      fontFamily: "Impact, Arial Black, sans-serif",
      fill: "#f6c34b",
      stroke: "#7a4300",
      strokeWidth: 6,
      shadowColor: "#301b00",
      shadowBlur: 14,
      style: "gold",
      decimals: 0,
    },
  },
  bankBar: { ...image("/assets/bank-bar.png", 627, 1168, 990), borderRadius: 18, shadowBlur: 10 },
  export: { format: "jpg", quality: 0.98 },
};

export function createDefaultPoster() {
  return structuredClone(DEFAULT_POSTER_CONFIG);
}

